### ISSUE TITLE
exception when calling add1

### ISSUE THREAD

**Issue by danirenae** [code-for-nashville/oss-intro-class#8]
Hey I found this weird bug and wanted to let you all know. Could you check out what I have here?

### Version
Node version v6.3.0
npm v 3.10.3
library version 1.0

### check out the error here:
```
        throw new Error('This is not an error')
        ^

Error: This is not an error
    at module.exports.add1 (/Users/daniadkins/workspace/codefornashville/oss-intro-class/oss-intro-class/index.js:52:15)
    at Object.<anonymous> (/Users/daniadkins/workspace/codefornashville/oss-intro-class/oss-intro-class/add1.js:2:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
```

**Comment by danirenae** [comment]
Hey I got this, y'all!

**Comment by danirenae** [comment]
This issue is complete.
